// import { SIGNUP_FORM_FIELD_KEY } from './frame/signup-form/';

export const USERLIST_KEY = {
  LOGIN: 'login',
  ID: 'id',
};


export const USERLIST_ACTION_TYPE = {
  USERLIST_UPLOAD_PENDING: 'USERLIST_TYPE.USERLIST_UPLOAD_PENDING',
  USERLIST_UPLOAD_SUCCESS: 'USERLIST_TYPE.USERLIST_UPLOAD_SUCCESS',
  USERLIST_UPLOAD_ERROR: 'USERLIST_TYPE.USERLIST_UPLOAD_ERROR',
  USERLIST_UPLOAD_RESET: 'USERLIST_TYPE.USERLIST_UPLOAD_RESET',
};

export const USERLIST_DATA_NAME = {
  LOGIN: 'login',
  ID: 'id',
};
